// GENERATED by scripts/hash-badwords.mjs. Do not edit by hand.
// SHA-256 hashes of lowercased words from src/config/badwords.local.txt (gitignored).
export const badWordHashes: readonly string[] = [
  "566f532d486c947709d3d0e6b7575af8380248db66dada211d58eb00ad585297",
  "6ac3c336e4094835293a3fed8a4b5fedde1b5e2626d9838fed50693bba00af0e",
  "85fc17f7069acd39a5c636cd0a6530651096128da447959f5e250824857dc559",
  "9ae315a94e428a7ee3b5e48adae6541965d93b86acf10ffa1c45b93b6fe577b4",
  "ad505b0be8a49b89273e307106fa42133cbd804456724c5e7635bd953215d92a",
  "c2c3b68b48832afd9a4dbdd474c1b6c81c8baecdb71446f9947dac72dd0fe93d",
  "d75a838dc758ba17f28bd8dbac605cb70c35465263d5733164521de2f7ef7926",
  "e512a05583448f44790783f986b1f36925c8cfc42338ca0e1caa637755bd15ae",
  "f50c51ed2315dcf3fa88181cf033f8029cac64f7dea4048327ca032ec102ea74"
];
